package commons

var FieldNames = map[string][]string{
	"DGI": []string{
		"DGI Record",
		"Set ID",
		"Diagnosis Codeing Method",
		"Diagnosis Code",
	},
	"MSH": []string{
		"MSH Record",
		"Field Separator",
		"Encoding Characters",
		"Sending Application",
		"Sending Facility",
		"Receiving Application",
		"Receiving Facility",
		"Date/Time of Message",
		"Security",
		"Message Type",
		"Message Control ID",
		"Processing ID",
		"Version ID",
		"Sequence Number",
		"Continuation Provider",
		"Accept Acknowledgement Type",
		"Application Acknowledgement Type",
		"Country Code",
		"Character Set",
		"Principal Language of Message",
		"Alternate Character Set Handling Scheme",
		"Conformance Statement ID",
	},
	"NTE": []string{
		"NTE Record",
		"Set ID",
		"Source of Comment",
		"Comment",
		"Comment Type",
	},
	"ORC": []string{
		"ORC Record",
		"Order Control",
		"Placer Order Number",
		"Filler Order Number",
		"Placer Group Number",
		"Order Status",
		"Response Flag",
		"Quantity/Timing",
		"Parent",
		"Date/Time of Transaction",
		"Entered By",
		"Verified By",
		"Medications Prescribing Provider",
		"Enterer's Location",
		"Call Back Phone Number",
		"Order Effective Date/Time",
		"Order Control Code Reason",
		"Entering Organization",
		"Entering Device",
		"Action by",
		"Advanced Beneficiary Notice Code",
		"Ordering Facility Name",
		"Ordering Facility Address",
		"Ordering Facility Phone Number",
		"Ordering Provider Address",
	},
	"PID": []string{
		"PID Record",
		"Set ID",
		"Patient ID",
		"Patient Identifier List",
		"Alternate Patient ID",
		"Patient Name",
		"Mother's Maiden Name",
		"Date/Time of Birth",
		"Sex",
		"Patient Alias",
		"Race",
		"Patient Address",
		"County Code",
		"Phone Number - Home",
		"Phone Number - Work",
		"Primary Language",
		"Marital Status",
		"Religion",
		"Patient Account Number",
		"SSN Number",
		"Driver's License Number",
		"Mother's Identifier",
		"Ethnic Group",
		"Birth Place",
		"Multiple Birth Indicator",
		"Birth Order",
		"Citizenship",
		"Veteran's Military Status",
		"Nationality",
		"Patient Death Date and Time",
		"Patient Death Indicator",
	},
	"RXE": []string{
		"RXE Record",
		"Quantity/Timing",
		"Give Code",
		"Give Amount - Minimum",
		"Give Amount - Maximum",
		"Give Units",
		"Give Dosage Form",
		"Provider's Administration  Instructions",
		"Deliver-to Location",
		"Substitution Status",
		"Dispense Amount",
		"Dispense Units",
		"Number of Refills",
		"Order Provider's DEA Number",
		"Pharmacist/Treatment Supplier's",
		"Prescription Number",
		"Number of Refills Remaining",
		"Number of Refills/Doses Dispensed",
		"Date/Time of Most Recent Refill or Dose Dispensed",
		"Total Daily Doses",
		"Needs Human Review",
		"Pharmacy/Treatment Supplier's Special Dispensing Instructions",
		"Give Per",
		"Give Rate Amount",
		"Give Rate Units",
		"Give Strength",
		"Give Strength Units",
		"Give Indicatoin",
		"Dispense Package Size",
		"Dispense Package Size Unit",
		"Dispense Package Method",
		"Supplementary Code",
		"Date/Time of Transaction",
		"Give Drug Strength Volume",
		"Give Drug Strength Volume Units",
		"Controlled Substance Schedule",
		"Formulary Status",
		"Pharmaceutical Substance  Alternative",
		"Pharmacy of Most Recent Fill",
		"Initial Dispense Amount",
		"Dispensing Pharmacy",
	},
	"RXR": []string{
		"RXR Record",
		"Route",
		"Site",
		"Administration Device",
		"Administration method",
		"Routing Instructions",
	},
	"TQ1": []string{
		"TQ1 Record",
		"Set ID",
		"Quantity",
		"Repeat Pattern",
		"Explicit Time",
		"Relative Time and Units",
		"Service Duration",
		"Start Date/Time",
		"End Date/Time",
		"Priority",
		"Condition Text",
		"Text Instruction",
		"Conjunction",
		"Occurrence Duration",
		"Total Occurrences",
	},
	"ZWA": []string{
		"ZWA Record",
		"unused",
		"First Filled Date",
		"Last Filled Date",
		"Date Written",
		"Expiration Date",
		"Day Supply",
		"Second Sig",
		"unused",
		"unused",
		"Dispense Quantity Remaining",
		"Dispense Quantity Remaining Unit",
		"Origin Code",
		"Legacy Pharmacy Name",
		"Legacy Pharmacy DEA Number",
		"unused",
		"Prescription Serial Number",
	},
}
